name: Join ISPO Working Group
description: Use this issue to join the ISPO Working Group
title: "[join] <your-name>"
labels: ["join-wg"]
assignees:
  - rrrutledge
  - spier
  - jeffabailey
  - JustinGOSSES
  - dellagustin-sap
body:
  - type: markdown
    attributes:
      value: |
        It would be great to have you in the ISPO Working Group!
        Please fill in your name in the title of the issue.
        Once you file the issue, an Admin will add you shortly.
        Join us also in the #ispo-working-group channel of the [InnerSource Commons Slack](https://app.slack.com/client/T04PXKRM0/C04DT6NQX7G).
  - type: input
    id: github-user
    attributes:
      label: GitHub User
      description: What is your GitHub username?
      placeholder: ex. spier
    validations:
      required: true
