---
name: Join ISPO Working Group
description: Use this issue to join the ISPO Working Group
title: Join ISPO Working Group
labels: ''
assignees:
  - rrrutledge
  - jeffabailey
  - JustinGOSSES
  - dellagustin-sap
---

It would be great to have you in the ISPO Working Group!

After you open this issue, one of the assignees will perform these steps to get you set up with the working group:

- [ ] Send an invite to to join the ["ispo working group" GitHub team](https://github.com/orgs/InnerSourceCommons/teams/ispo-working-group).
Click through all of the confirmations and warnings.
- [ ] Find the person's email from their Slack profile and add them to the [recurring meeting](https://calendar.google.com/calendar/u/0/r/eventedit/MHFhYnNnOXJrMDFscmw4ZHRzcW12Z28zcDRfMjAyNDA1MDZUMTUwMDAwWiBjXzYyNjk0ZjQxNDA1NWFjNTY5ZTVjYjEyZGFmYmIwODkwY2EyMmYzNjQwYjE3N2E0YjEwYjUzMTcxZmJjOWJkZDRAZw) (this and future events).
- [ ] Close the issue.

That's it!
